### ISSUE TITLE
不同的设备上表现不一致

### ISSUE THREAD

**Issue by Brances** [91renb/BRPickerView#120]
![image](https://user-images.githubusercontent.com/10275640/72445077-1efe1900-37ec-11ea-94bd-cb7f6fa1514b.png)
如上图所示：在iphone 11 上直接被挡住了，在7上还算正常，但是挡住背景的颜色了

**Comment by 91renb** [comment]
你的需求是什么，这个与你自定义的背景颜色有关，可以根据你的需求自定义样式，在iPhone11上要注意下是否使用了动态颜色。




            
            
                
                    
                            
                                
                            
                            
                                2693475166
                            
                    
                        
                            
                                    邮箱：2693475166@qq.com
                            
                        
                
            
        


在2020年01月15日 23:11，coderly 写道： 
如上图所示：在iphone 11 上直接被挡住了，在7上还算正常，但是挡住背景的颜色了

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/91renb/BRPickerView/issues/120?email_source=notifications\u0026email_token=AFR67T6N5CPB3NXJVS5LDTDQ54RSFA5CNFSM4KHFCHY2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IGMC7EQ",
"url": "https://github.com/91renb/BRPickerView/issues/120?email_source=notifications\u0026email_token=AFR67T6N5CPB3NXJVS5LDTDQ54RSFA5CNFSM4KHFCHY2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IGMC7EQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Brances** [comment]
@91renb  多谢提醒，我的模拟器是13.0以上了，到了晚上自动开启了暗黑模式，背景颜色的问题也解决了

**Comment by Brances** [comment]
@91renb  User Interface Style  已经设置了Light ，但是iOS13好像还是有问题，xcode11.3,请问是去哪里设置动态颜色，我完全参照的demo用法

**Comment by Brances** [comment]
手动改_pickerColor这个才行
