### ISSUE TITLE
建议新增一个清除按钮

### ISSUE THREAD

**Issue by Libogold** [91renb/BRPickerView#121]
在取消旁边新增一个清除按钮，清除选中数据。

**Comment by 91renb** [comment]
这个可以自定义来实现，自定义弹框视图，新增清除按钮，点击清除按钮重置选择的值即可。




            
            
                
                    
                            
                                
                            
                            
                                2693475166
                            
                    
                        
                            
                                    邮箱：2693475166@qq.com
                            
                        
                
            
        


在2020年01月19日 18:03，Libogold 写道： 在取消旁边新增一个清除按钮，清除选中数据。

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/91renb/BRPickerView/issues/121?email_source=notifications\u0026email_token=AFR67T25ED3L337FUYNFSALQ6QQOBA5CNFSM4KIYJU7KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IHFJGRA",
"url": "https://github.com/91renb/BRPickerView/issues/121?email_source=notifications\u0026email_token=AFR67T25ED3L337FUYNFSALQ6QQOBA5CNFSM4KIYJU7KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IHFJGRA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Libogold** [comment]
哦哦，找到了谢谢作者。功能强大又完善，膜拜
